### ISSUE TITLE
Blogger Not Working with Open LiveWriter

### ISSUE THREAD

**Issue by Happy4OLW** [OpenLiveWriter/OpenLiveWriter#837]
I'm trying to send a draft to blogger and it will not send.  It appears like it is; the "Publishing Your Post" box pops up for about 1 second but when I check Blogger the draft is not there.  Any help would be appreciated please and thanks!

**Comment by nvella** [comment]
Hi there @Happy4OLW. Thanks for showing your support!

I've just attempted to reproduce the issue you described and was not successful; my draft showed up on blogger.com with the Draft label in the right column. Would I be able to ask a few questions about your setup?

- What version of OLW you're running? (the Microsoft Store version, website version or a development version)
- Are any images in the post you're attempting to publish a draft for?
- Would there be anything 'out of the ordinary' with your Blogger blog, as in have you set it up in a substantially different way to how a regular Blogger blog is setup?

Kind regards, Nick

**Comment by Happy4OLW** [comment]
Thank you for responding, Nick  I just got home from work but will attempt to answer your questions.  The version I am using is Build 0.6.2.0.  Yes, there are images in the post. There is nothing different to how a blogger blog is usually set up.  

Thanks for you assistance.

**Comment by deanboman** [comment]
Hi,  I am having the same exact problem.  I am also using 0.6.2.0.  I have tried the Microsoft store version and also the website version with the same response.  The "Publishing your Post" dialog box comes up for  a couple seconds then goes away.  No error message or anything but the post does not upload to Blogger.
Thanks.

**Comment by nvella** [comment]
Hi again @Happy4OLW and @deanboman. I have been able to reproduce the issue on the Windows Store version of Open Live Writer; posts and drafts with images fail to publish to Blogger, failing silently. This would be the same issue as #786, which was fixed in PR #810. The next version released to the Windows Store and on the website should have the fixes for these issues.

The development builds available from https://ci.appveyor.com/project/dotnetfoundation/openlivewriter do have the fixes for these issues, however installing and using them isn't the most user-friendly experience at the moment (bug in auto updater continuously spawns new instances -#838) so I'd recommend holding off and waiting until the next official release for the time being.

I'll close this issue for now, but please don't hesitate to get back in touch if you have any more queries. Cheers 👍

**Comment by Happy4OLW** [comment]
Hi Nick,

Not sure if I can add to this now that it's closed but uninstalling the app and redownloading from the store did not work.  Neither did installing it directly onto my computer using the download from the OLW website.  Looks like I'm going to half to find another blog editor. Thanks for trying.

**Comment by nvella** [comment]
Hi again @Happy4OLW. 

Please don't take me closing this issue as myself dismissing your concerns, and also please don't hesitate to reply to this or any issue on this project if you feel you have feedback or more information to the issue at hand.

I closed this issue because although it's currently not fixed in the Store or Website versions of OLW, a fix has been developed and applied to the code of the application that developers work on. As I am only a contributor myself, and not a project maintainer, I unfortunately do not currently have a time-frame as to when an update will be released onto the Store or Website. 

I do understand your frustration and I wish you could get your hands on this fix as soon as possible, however as Open Live Writer is ultimately a volunteer-run project the maintainers can only author a new release to the Store or Website when they have the free time available themselves. I offer my apologies.

**Comment by Happy4OLW** [comment]
Nick, please do not misunderstand me.  In no way am I upset with you for closing the issue. I just wasn't certain if I would still be able to add to it after it's closure.  At work we are not allowed to do that so I wasn't sure how it worked here.  Thanks for letting me know it's ok.

I took from your earlier response that the Microsoft store version was already updated and working but I can see now that I misread your reply and you were actually informing me that the new release will be available in the Store (and on the OLW website) at some point in the future.

I also want to add that I am not frustrated at all.  I understand that this is a voluntary effort and I did not mean to come across as being upset or angry that nothing was being done.   I apologize for giving you that impression.  I know everyone is working as much as they are able to get things working again.  Thanks again for your effort!

**Comment by Happy4OLW** [comment]
**_>>I also want to add that I am not frustrated at all. I understand that this is a voluntary effort and I did not mean to come across as being upset or angry that nothing was being done<<_**

Let me reword that, lol .... I'm not upset that it's not yet fixed.  I realize everyone is doing as much as they are able to do to fix the situation.  When I read that line back to myself again, I feel as if it may have sounded like I was saying nobody was working to fix it but I know there are many volunteers working on a solution.

Cheers!

**Comment by Bamse61** [comment]
I too have this problem and would love to solve it. I'm using Win10 and 0.6.2 of OLW
